
import React from 'react';

const AboutView: React.FC = () => {
  return (
    <div>
      <header className="pb-4 border-b border-gray-200 dark:border-gray-700">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white">About Zenith Social</h1>
        <p className="text-md text-gray-500 dark:text-gray-400">Your all-in-one social media management platform.</p>
      </header>

      <article className="mt-6 prose dark:prose-invert lg:prose-xl max-w-none">
        <p>
          Zenith Social is a comprehensive Social Media Management (SMM) platform designed to empower brands, businesses, and individuals to streamline their social media presence. Our mission is to provide powerful, intuitive tools that make scheduling posts, analyzing performance, and managing multiple social accounts effortless.
        </p>
        <h2>Our Features</h2>
        <ul>
          <li><strong>Content Planner:</strong> Visualize your content strategy with our intuitive drag-and-drop calendar.</li>
          <li><strong>AI-Powered Content Generation:</strong> Overcome writer's block with creative post ideas generated by Gemini.</li>
          <li><strong>Bulk Scheduling:</strong> Save time by importing and scheduling multiple posts at once with our CSV import feature.</li>
          <li><strong>In-Depth Analytics:</strong> Track your performance across all platforms with a unified dashboard and beautiful charts.</li>
          <li><strong>Multi-Account Management:</strong> Connect and manage all your profiles from Facebook, Instagram, X, LinkedIn, and more in one place.</li>
        </ul>
        <p>
          Whether you're a small business owner, a marketing professional, or a content creator, Zenith Social provides the tools you need to grow your audience and elevate your brand.
        </p>
      </article>
    </div>
  );
};

export default AboutView;
